<?php

declare(strict_types=1);

/**
 * Site-wide copy settings (text labels, CTAs, forms, thanks, SEO).
 */
function cms_copy_setting_keys(): array
{
    return [
        'home_hero_btn_primary_text' => 'Home hero — primary button text',
        'home_hero_btn_primary_url' => 'Home hero — primary button link',
        'home_hero_btn_secondary_text' => 'Home hero — secondary button text',
        'home_hero_btn_secondary_url' => 'Home hero — secondary button link',
        'home_hero_scroll_text' => 'Home hero — scroll hint text',
        'home_link_about_text' => 'Home — “Meet the studio” link text',
        'home_link_about_url' => 'Home — “Meet the studio” URL',
        'home_link_services_text' => 'Home — services link text',
        'home_link_services_url' => 'Home — services link URL',
        'home_link_work_text' => 'Home — portfolio link text',
        'home_link_work_url' => 'Home — portfolio link URL',
        'home_link_process_text' => 'Home — process link text',
        'home_link_process_url' => 'Home — process link URL',
        'home_link_journal_text' => 'Home — journal link text',
        'home_link_journal_url' => 'Home — journal link URL',
        'studio_cta_text' => 'Studio page — CTA paragraph',
        'studio_cta_btn_text' => 'Studio page — CTA button text',
        'studio_cta_btn_url' => 'Studio page — CTA button URL',
        'services_cta_eyebrow' => 'Services page — CTA eyebrow',
        'services_cta_title' => 'Services page — CTA title',
        'services_cta_lead' => 'Services page — CTA text',
        'services_cta_sub' => 'Services page — CTA subheadline',
        'services_cta_btn_text' => 'Services page — CTA button text',
        'services_cta_btn_url' => 'Services page — CTA button URL',
        'services_cta_btn2_text' => 'Services page — secondary CTA button text',
        'services_cta_btn2_url' => 'Services page — secondary CTA button URL',
        'services_faq_eyebrow' => 'Services page — FAQ eyebrow',
        'services_faq_title' => 'Services page — FAQ title',
        'work_cta_text' => 'Work page — CTA paragraph',
        'work_cta_btn_text' => 'Work page — CTA button text',
        'work_cta_btn_url' => 'Work page — CTA button URL',
        'work_cta_final_eyebrow' => 'Work page — final CTA eyebrow',
        'work_cta_final_title' => 'Work page — final CTA title',
        'work_cta_final_sub' => 'Work page — final CTA subheadline',
        'work_cta_final_btn_text' => 'Work page — final CTA primary button',
        'work_cta_final_btn2_text' => 'Work page — final CTA secondary button',
        'work_featured_eyebrow' => 'Work page — featured section eyebrow',
        'work_stats_eyebrow' => 'Work page — stats section eyebrow',
        'work_stats_title' => 'Work page — stats section title',
        'work_categories_eyebrow' => 'Work page — categories eyebrow',
        'work_categories_title' => 'Work page — categories title',
        'work_testimonials_eyebrow' => 'Work page — testimonials eyebrow',
        'work_testimonials_title' => 'Work page — testimonials title',
        'work_timeline_eyebrow' => 'Work page — timeline eyebrow',
        'work_timeline_title' => 'Work page — timeline title',
        'work_timeline_intro' => 'Work page — timeline intro',
        'work_trust_eyebrow' => 'Work page — trust section eyebrow',
        'work_trust_title' => 'Work page — trust section title',
        'work_filter_all' => 'Work page — filter “All”',
        'work_filter_residential' => 'Work page — filter “Residential”',
        'work_filter_commercial' => 'Work page — filter “Commercial”',
        'work_filter_retail' => 'Work page — filter “Retail”',
        'process_cta_eyebrow' => 'Process page — CTA eyebrow',
        'process_cta_title' => 'Process page — CTA title',
        'process_cta_sub' => 'Process page — CTA subheadline',
        'process_cta_text' => 'Process page — CTA paragraph',
        'process_cta_btn_text' => 'Process page — CTA button text',
        'process_cta_btn_url' => 'Process page — CTA button URL',
        'process_cta_btn2_text' => 'Process page — secondary CTA button text',
        'process_cta_btn2_url' => 'Process page — secondary CTA button URL',
        'process_faq_eyebrow' => 'Process page — FAQ eyebrow',
        'process_faq_title' => 'Process page — FAQ title',
        'journal_stat_readers' => 'Journal page — monthly readers stat',
        'journal_newsletter_title' => 'Journal page — newsletter heading',
        'journal_newsletter_lead' => 'Journal page — newsletter intro',
        'journal_cta_eyebrow' => 'Journal page — CTA eyebrow',
        'journal_cta_title' => 'Journal page — CTA heading',
        'journal_cta_sub' => 'Journal page — CTA subheadline',
        'journal_cta_text' => 'Journal page — CTA paragraph',
        'journal_cta_btn_text' => 'Journal page — CTA button text',
        'journal_cta_btn_url' => 'Journal page — CTA button URL',
        'journal_cta_btn2_text' => 'Journal page — secondary CTA button text',
        'journal_cta_btn2_url' => 'Journal page — secondary CTA button URL',
        'journal_faq_q1' => 'Journal page — FAQ 1 question',
        'journal_faq_a1' => 'Journal page — FAQ 1 answer',
        'journal_faq_q2' => 'Journal page — FAQ 2 question',
        'journal_faq_a2' => 'Journal page — FAQ 2 answer',
        'journal_faq_q3' => 'Journal page — FAQ 3 question',
        'journal_faq_a3' => 'Journal page — FAQ 3 answer',
        'journal_faq_q4' => 'Journal page — FAQ 4 question',
        'journal_faq_a4' => 'Journal page — FAQ 4 answer',
        'contact_cta_title' => 'Contact page — CTA heading',
        'contact_cta_sub' => 'Contact page — CTA subheadline',
        'contact_cta_btn_text' => 'Contact page — primary CTA button',
        'contact_cta_btn_url' => 'Contact page — primary CTA URL',
        'contact_cta_btn2_text' => 'Contact page — secondary CTA button',
        'contact_cta_btn2_url' => 'Contact page — secondary CTA URL',
        'contact_wa_lead' => 'Contact page — WhatsApp intro',
        'thanks_eyebrow' => 'Thank you page — eyebrow',
        'thanks_title' => 'Thank you page — title',
        'thanks_note_html' => 'Thank you page — message (form only)',
        'thanks_note_php_html' => 'Thank you page — message (saved via PHP)',
        'thanks_btn_home_text' => 'Thank you — home button',
        'thanks_btn_work_text' => 'Thank you — work button',
        'form_label_name' => 'Forms — Name label',
        'form_label_email' => 'Forms — Email label',
        'form_label_phone' => 'Forms — Phone label',
        'form_label_project_type' => 'Forms — Project type label',
        'form_label_message' => 'Forms — Message label',
        'form_placeholder_name' => 'Forms — Name placeholder',
        'form_placeholder_email' => 'Forms — Email placeholder',
        'form_placeholder_phone' => 'Forms — Phone placeholder',
        'form_placeholder_project_type' => 'Forms — Project type placeholder',
        'form_placeholder_message' => 'Forms — Message placeholder',
        'form_note_contact' => 'Contact form — note under fields',
        'form_submit_text' => 'Forms — submit button text',
        'legal_privacy_html' => 'Privacy policy (HTML)',
        'legal_terms_html' => 'Terms of use (HTML)',
        'seo_home_title' => 'SEO — Home page title',
        'seo_home_description' => 'SEO — Home meta description',
        'seo_studio_title' => 'SEO — Studio title',
        'seo_studio_description' => 'SEO — Studio description',
        'seo_services_title' => 'SEO — Services title',
        'seo_services_description' => 'SEO — Services description',
        'seo_work_title' => 'SEO — Work title',
        'seo_work_description' => 'SEO — Work description',
        'seo_process_title' => 'SEO — Process title',
        'seo_process_description' => 'SEO — Process description',
        'seo_journal_title' => 'SEO — Journal title',
        'seo_journal_description' => 'SEO — Journal description',
        'seo_contact_title' => 'SEO — Contact title',
        'seo_contact_description' => 'SEO — Contact description',
        'seo_privacy_title' => 'SEO — Privacy title',
        'seo_privacy_description' => 'SEO — Privacy description',
        'seo_terms_title' => 'SEO — Terms title',
        'seo_terms_description' => 'SEO — Terms description',
        'seo_thanks_title' => 'SEO — Thank you title',
        'seo_thanks_description' => 'SEO — Thank you description',
    ];
}

function cms_copy_defaults(): array
{
    return [
        'home_hero_btn_primary_text' => 'Start Your Project',
        'home_hero_btn_primary_url' => '#consult',
        'home_hero_btn_secondary_text' => 'View Our Work',
        'home_hero_btn_secondary_url' => 'work.html',
        'home_hero_scroll_text' => 'Discover',
        'home_link_about_text' => 'Meet the studio',
        'home_link_about_url' => 'studio.html',
        'home_link_services_text' => 'Explore services',
        'home_link_services_url' => 'services.html',
        'home_link_work_text' => 'Full portfolio',
        'home_link_work_url' => 'work.html',
        'home_link_process_text' => 'Detailed methodology',
        'home_link_process_url' => 'process.html',
        'home_link_journal_text' => 'View journal',
        'home_link_journal_url' => 'journal.html',
        'studio_cta_text' => 'See how we translate intent into drawings, models, and built work.',
        'studio_cta_btn_text' => 'Our process',
        'studio_cta_btn_url' => 'process.html',
        'services_cta_eyebrow' => 'Next project',
        'services_cta_title' => "Let's Build Something Extraordinary.",
        'services_cta_sub' => 'Architecture · Interiors · Construction · Turnkey Delivery',
        'services_cta_lead' => 'Share your site, scope, and timeline — we will recommend design-only, approval support, or full turnkey delivery.',
        'services_cta_btn_text' => 'Book consultation',
        'services_cta_btn_url' => 'contact.html',
        'services_cta_btn2_text' => 'Get project estimate',
        'services_cta_btn2_url' => 'contact.html',
        'work_cta_text' => 'Discuss a commission with the studio.',
        'work_cta_btn_text' => 'Start a project',
        'work_cta_btn_url' => 'contact.html',
        'work_cta_final_eyebrow' => 'Next project',
        'work_cta_final_title' => 'Ready To Build Something Exceptional?',
        'work_cta_final_sub' => "Architecture.\nInteriors.\nConstruction.\nTurnkey Delivery.",
        'work_cta_final_btn_text' => 'Start Your Project',
        'work_cta_final_btn2_text' => 'Book Consultation',
        'work_featured_eyebrow' => 'Featured commission',
        'work_stats_eyebrow' => 'Experience',
        'work_stats_title' => 'Built on measurable impact',
        'work_categories_eyebrow' => 'Disciplines',
        'work_categories_title' => 'Explore by category',
        'work_testimonials_eyebrow' => 'Clients',
        'work_testimonials_title' => 'Trusted for execution & design',
        'work_timeline_eyebrow' => 'Growth',
        'work_timeline_title' => 'A decade of delivery',
        'work_timeline_intro' => 'Projects completed year by year — evidence of sustained practice and expanding scope.',
        'work_trust_eyebrow' => 'Why Archevo',
        'work_trust_title' => 'Why clients choose Archevo',
        'work_filter_all' => 'All',
        'work_filter_residential' => 'Residential',
        'work_filter_commercial' => 'Commercial',
        'work_filter_retail' => 'Retail',
        'process_cta_eyebrow' => 'Next step',
        'process_cta_title' => "Let's Build With Confidence.",
        'process_cta_sub' => 'Architecture · Interiors · Construction · Delivered Through A Proven Process',
        'process_cta_text' => 'Request a PDF overview of deliverables and typical timelines for your project type.',
        'process_cta_btn_text' => 'Book consultation',
        'process_cta_btn_url' => 'contact.html',
        'process_cta_btn2_text' => 'Discuss your project',
        'process_cta_btn2_url' => 'contact.html',
        'journal_stat_readers' => '12K+',
        'journal_newsletter_title' => 'Join The Design Conversation',
        'journal_newsletter_lead' => 'Architecture insights, project stories, design trends, and material knowledge — delivered with care.',
        'journal_cta_eyebrow' => 'Work with us',
        'journal_cta_title' => "Let's Create Better Spaces Together",
        'journal_cta_sub' => 'Architecture · Interiors · Construction · Ideas That Inspire',
        'journal_cta_text' => 'For press, collaborations, or speaking invitations, reach the studio directly.',
        'journal_cta_btn_text' => 'Start your project',
        'journal_cta_btn_url' => 'contact.html',
        'journal_cta_btn2_text' => 'Contact the studio',
        'journal_cta_btn2_url' => 'contact.html',
        'journal_faq_q1' => 'How often do you publish new articles?',
        'journal_faq_a1' => 'We publish when we have meaningful insights from practice — typically monthly, with deeper essays on materials, process, and project lessons.',
        'journal_faq_q2' => 'Can I republish or cite your articles?',
        'journal_faq_a2' => 'Yes, with attribution and a link to the original. For syndication or press use, contact the studio directly.',
        'journal_faq_q3' => 'Who writes the journal?',
        'journal_faq_a3' => 'Articles are authored by our founders, architects, and design team — grounded in real projects and site experience.',
        'journal_faq_q4' => 'How do I subscribe to updates?',
        'journal_faq_a4' => 'Use the newsletter form on this page or enquire via contact — we share insights, project stories, and material knowledge.',
        'contact_cta_title' => "Let's Build Your Vision Together",
        'contact_cta_sub' => 'Architecture · Interiors · Construction · Turnkey Delivery',
        'contact_cta_btn_text' => 'Book consultation',
        'contact_cta_btn_url' => '#cnt-enquiry-form',
        'contact_cta_btn2_text' => 'Start your project',
        'contact_cta_btn2_url' => '#cnt-enquiry-form',
        'contact_wa_lead' => 'Prefer a quick chat? Message us on WhatsApp — we typically reply within a few hours on business days.',
        'thanks_eyebrow' => 'Enquiry received',
        'thanks_title' => 'Thank you',
        'thanks_note_html' => 'Your message has been sent. We typically reply within two business days.',
        'thanks_note_php_html' => 'Your enquiry was saved. We typically reply within two business days.',
        'thanks_btn_home_text' => 'Back to home',
        'thanks_btn_work_text' => 'View work',
        'form_label_name' => 'Name',
        'form_label_email' => 'Email',
        'form_label_phone' => 'Phone',
        'form_label_project_type' => 'Project type',
        'form_label_message' => 'Message',
        'form_placeholder_name' => 'Your name',
        'form_placeholder_email' => 'you@email.com',
        'form_placeholder_phone' => '+91 …',
        'form_placeholder_project_type' => 'Residence / Office / Retail…',
        'form_placeholder_message' => 'Site location, approximate area, timeline, budget band…',
        'form_note_contact' => 'We respond within two business days. Your details are stored securely for the studio team.',
        'form_submit_text' => 'Send enquiry',
        'legal_privacy_html' => '<p class="section-lead">Last updated: January 2026. This policy describes how Archevo Design and Archevo Infra Edge Pvt Ltd (“we”) handle information when you use this website or contact us.</p><h2>Information we collect</h2><p>When you submit an enquiry through our website contact form, we collect the details you provide (such as your name, email address, phone number if given, project type if given, and message). Each submission is stored securely on our server and a notification is emailed to our studio team so we can respond. If you contact us directly by email or phone, we receive the information you choose to share.</p><h2>How we use it</h2><p>We use contact information only to respond to enquiries, prepare proposals, and manage projects. We do not sell personal data.</p><h2>Retention</h2><p>Enquiry records are kept for as long as needed to fulfil our contract and legal obligations, then deleted or anonymised according to our internal policy.</p><h2>Your rights</h2><p>Depending on applicable law, you may request access, correction, or deletion of your personal data. Contact <a href="mailto:archevodesign6@gmail.com">archevodesign6@gmail.com</a>.</p><h2>Changes</h2><p>We may update this page periodically. Continued use of the site after changes constitutes acceptance of the updated policy.</p>',
        'legal_terms_html' => '<p class="section-lead">By using this website you agree to these terms. Content, images, and text are owned by Archevo Design unless otherwise credited.</p><p>Information on this site is for general guidance and does not constitute a contract until agreed in writing. We reserve the right to update these terms at any time.</p>',
        'seo_home_title' => 'Archevo Design | Architecture & Interior Design · Rajkot',
        'seo_home_description' => 'Archevo Design — integrated design, civil construction, interiors, and turnkey delivery across Gujarat.',
        'seo_studio_title' => 'Studio | Archevo Design',
        'seo_studio_description' => 'Meet Archevo Design — philosophy, team, and integrated design & build in Rajkot, Gujarat.',
        'seo_services_title' => 'Services | Archevo Design',
        'seo_services_description' => 'Plan approvals, interiors, civil construction, and turnkey projects from Archevo Design.',
        'seo_work_title' => 'Work | Archevo Design',
        'seo_work_description' => 'Selected residential, commercial, and retail projects by Archevo Design.',
        'seo_process_title' => 'Process | Archevo Design',
        'seo_process_description' => 'How Archevo Design moves from brief to handover — clear phases and accountability.',
        'seo_journal_title' => 'Journal | Archevo Design',
        'seo_journal_description' => 'Ideas on materiality, process, and the culture of space from Archevo Design.',
        'seo_contact_title' => 'Contact | Archevo Design',
        'seo_contact_description' => 'Contact Archevo Design in Rajkot for architecture and interior design enquiries.',
        'seo_privacy_title' => 'Privacy | Archevo Design',
        'seo_privacy_description' => 'Privacy policy for Archevo Design website.',
        'seo_terms_title' => 'Terms | Archevo Design',
        'seo_terms_description' => 'Terms of use for the Archevo Design website.',
        'seo_thanks_title' => 'Thank you | Archevo Design',
        'seo_thanks_description' => 'Thank you for contacting Archevo Design.',
    ];
}

function cms_build_copy_array(array $settings): array
{
    $defaults = cms_copy_defaults();
    $out = [];
    foreach (cms_copy_setting_keys() as $key => $label) {
        $out[$key] = trim((string) ($settings[$key] ?? '')) !== ''
            ? trim((string) $settings[$key])
            : ($defaults[$key] ?? '');
    }

    return $out;
}
