<?php

declare(strict_types=1);

/**
 * Site-wide copy settings (text labels, CTAs, forms, thanks, SEO).
 */
function cms_copy_setting_keys(): array
{
    return [
        'home_hero_btn_primary_text' => 'Home hero — primary button text',
        'home_hero_btn_primary_url' => 'Home hero — primary button link',
        'home_hero_btn_secondary_text' => 'Home hero — secondary button text',
        'home_hero_btn_secondary_url' => 'Home hero — secondary button link',
        'home_hero_scroll_text' => 'Home hero — scroll hint text',
        'home_link_about_text' => 'Home — “Meet the studio” link text',
        'home_link_about_url' => 'Home — “Meet the studio” URL',
        'home_link_services_text' => 'Home — services link text',
        'home_link_services_url' => 'Home — services link URL',
        'home_link_work_text' => 'Home — portfolio link text',
        'home_link_work_url' => 'Home — portfolio link URL',
        'home_link_process_text' => 'Home — process link text',
        'home_link_process_url' => 'Home — process link URL',
        'home_link_journal_text' => 'Home — journal link text',
        'home_link_journal_url' => 'Home — journal link URL',
        'studio_cta_text' => 'Studio page — CTA paragraph',
        'studio_cta_btn_text' => 'Studio page — CTA button text',
        'studio_cta_btn_url' => 'Studio page — CTA button URL',
        'services_cta_eyebrow' => 'Services page — CTA eyebrow',
        'services_cta_title' => 'Services page — CTA title',
        'services_cta_lead' => 'Services page — CTA text',
        'services_cta_btn_text' => 'Services page — CTA button text',
        'services_cta_btn_url' => 'Services page — CTA button URL',
        'work_cta_text' => 'Work page — CTA paragraph',
        'work_cta_btn_text' => 'Work page — CTA button text',
        'work_cta_btn_url' => 'Work page — CTA button URL',
        'work_filter_all' => 'Work page — filter “All”',
        'work_filter_residential' => 'Work page — filter “Residential”',
        'work_filter_commercial' => 'Work page — filter “Commercial”',
        'work_filter_retail' => 'Work page — filter “Retail”',
        'process_cta_text' => 'Process page — CTA paragraph',
        'process_cta_btn_text' => 'Process page — CTA button text',
        'process_cta_btn_url' => 'Process page — CTA button URL',
        'journal_cta_text' => 'Journal page — CTA paragraph',
        'journal_cta_btn_text' => 'Journal page — CTA button text',
        'journal_cta_btn_url' => 'Journal page — CTA button URL',
        'thanks_eyebrow' => 'Thank you page — eyebrow',
        'thanks_title' => 'Thank you page — title',
        'thanks_note_html' => 'Thank you page — message (form only)',
        'thanks_note_php_html' => 'Thank you page — message (saved via PHP)',
        'thanks_btn_home_text' => 'Thank you — home button',
        'thanks_btn_work_text' => 'Thank you — work button',
        'form_label_name' => 'Forms — Name label',
        'form_label_email' => 'Forms — Email label',
        'form_label_phone' => 'Forms — Phone label',
        'form_label_project_type' => 'Forms — Project type label',
        'form_label_message' => 'Forms — Message label',
        'form_placeholder_name' => 'Forms — Name placeholder',
        'form_placeholder_email' => 'Forms — Email placeholder',
        'form_placeholder_phone' => 'Forms — Phone placeholder',
        'form_placeholder_project_type' => 'Forms — Project type placeholder',
        'form_placeholder_message' => 'Forms — Message placeholder',
        'form_note_contact' => 'Contact form — note under fields',
        'form_submit_text' => 'Forms — submit button text',
        'legal_privacy_html' => 'Privacy policy (HTML)',
        'legal_terms_html' => 'Terms of use (HTML)',
        'seo_home_title' => 'SEO — Home page title',
        'seo_home_description' => 'SEO — Home meta description',
        'seo_studio_title' => 'SEO — Studio title',
        'seo_studio_description' => 'SEO — Studio description',
        'seo_services_title' => 'SEO — Services title',
        'seo_services_description' => 'SEO — Services description',
        'seo_work_title' => 'SEO — Work title',
        'seo_work_description' => 'SEO — Work description',
        'seo_process_title' => 'SEO — Process title',
        'seo_process_description' => 'SEO — Process description',
        'seo_journal_title' => 'SEO — Journal title',
        'seo_journal_description' => 'SEO — Journal description',
        'seo_contact_title' => 'SEO — Contact title',
        'seo_contact_description' => 'SEO — Contact description',
        'seo_privacy_title' => 'SEO — Privacy title',
        'seo_privacy_description' => 'SEO — Privacy description',
        'seo_terms_title' => 'SEO — Terms title',
        'seo_terms_description' => 'SEO — Terms description',
        'seo_thanks_title' => 'SEO — Thank you title',
        'seo_thanks_description' => 'SEO — Thank you description',
    ];
}

function cms_copy_defaults(): array
{
    return [
        'home_hero_btn_primary_text' => 'View selected work',
        'home_hero_btn_primary_url' => '#projects',
        'home_hero_btn_secondary_text' => 'Start a project',
        'home_hero_btn_secondary_url' => 'contact.html',
        'home_hero_scroll_text' => 'Discover',
        'home_link_about_text' => 'Meet the studio',
        'home_link_about_url' => 'studio.html',
        'home_link_services_text' => 'Explore services',
        'home_link_services_url' => 'services.html',
        'home_link_work_text' => 'Full portfolio',
        'home_link_work_url' => 'work.html',
        'home_link_process_text' => 'Detailed methodology',
        'home_link_process_url' => 'process.html',
        'home_link_journal_text' => 'View journal',
        'home_link_journal_url' => 'journal.html',
        'studio_cta_text' => 'See how we translate intent into drawings, models, and built work.',
        'studio_cta_btn_text' => 'Our process',
        'studio_cta_btn_url' => 'process.html',
        'services_cta_eyebrow' => 'Brief us',
        'services_cta_title' => 'Tell us about your site',
        'services_cta_lead' => 'We will suggest an engagement model — design-only, design-build, or phased rollout — matched to your timeline.',
        'services_cta_btn_text' => 'Book a call',
        'services_cta_btn_url' => 'contact.html',
        'work_cta_text' => 'Discuss a commission with the studio.',
        'work_cta_btn_text' => 'Start a project',
        'work_cta_btn_url' => 'contact.html',
        'work_filter_all' => 'All',
        'work_filter_residential' => 'Residential',
        'work_filter_commercial' => 'Commercial',
        'work_filter_retail' => 'Retail',
        'process_cta_text' => 'Every project begins with a conversation about site, ambition, and calendar.',
        'process_cta_btn_text' => 'Enquire',
        'process_cta_btn_url' => 'contact.html',
        'journal_cta_text' => 'For press, collaborations, or speaking invitations, reach the studio directly.',
        'journal_cta_btn_text' => 'Contact us',
        'journal_cta_btn_url' => 'contact.html',
        'thanks_eyebrow' => 'Enquiry received',
        'thanks_title' => 'Thank you',
        'thanks_note_html' => 'Your message has been sent. We typically reply within two business days.',
        'thanks_note_php_html' => 'Your enquiry was saved. We typically reply within two business days.',
        'thanks_btn_home_text' => 'Back to home',
        'thanks_btn_work_text' => 'View work',
        'form_label_name' => 'Name',
        'form_label_email' => 'Email',
        'form_label_phone' => 'Phone',
        'form_label_project_type' => 'Project type',
        'form_label_message' => 'Message',
        'form_placeholder_name' => 'Your name',
        'form_placeholder_email' => 'you@email.com',
        'form_placeholder_phone' => '+91 …',
        'form_placeholder_project_type' => 'Residence / Office / Retail…',
        'form_placeholder_message' => 'Site location, approximate area, timeline, budget band…',
        'form_note_contact' => 'We respond within two business days. Your details are stored securely for the studio team.',
        'form_submit_text' => 'Send enquiry',
        'legal_privacy_html' => '<p class="section-lead">Last updated: January 2026. This policy describes how Archevo Design and Archevo Infra Edge Pvt Ltd (“we”) handle information when you use this website or contact us.</p><h2>Information we collect</h2><p>When you submit an enquiry through our website contact form, we collect the details you provide (such as your name, email address, phone number if given, project type if given, and message). Each submission is stored securely on our server and a notification is emailed to our studio team so we can respond. If you contact us directly by email or phone, we receive the information you choose to share.</p><h2>How we use it</h2><p>We use contact information only to respond to enquiries, prepare proposals, and manage projects. We do not sell personal data.</p><h2>Retention</h2><p>Enquiry records are kept for as long as needed to fulfil our contract and legal obligations, then deleted or anonymised according to our internal policy.</p><h2>Your rights</h2><p>Depending on applicable law, you may request access, correction, or deletion of your personal data. Contact <a href="mailto:archevodesign6@gmail.com">archevodesign6@gmail.com</a>.</p><h2>Changes</h2><p>We may update this page periodically. Continued use of the site after changes constitutes acceptance of the updated policy.</p>',
        'legal_terms_html' => '<p class="section-lead">By using this website you agree to these terms. Content, images, and text are owned by Archevo Infra Edge Pvt Ltd unless otherwise credited.</p><p>Information on this site is for general guidance and does not constitute a contract until agreed in writing. We reserve the right to update these terms at any time.</p>',
        'seo_home_title' => 'Archevo Design | Architecture & Interior Design · Rajkot',
        'seo_home_description' => 'Archevo Design — integrated design, civil construction, interiors, and turnkey delivery across Gujarat.',
        'seo_studio_title' => 'Studio | Archevo Design',
        'seo_studio_description' => 'Meet Archevo Design — philosophy, team, and integrated design & build in Rajkot, Gujarat.',
        'seo_services_title' => 'Services | Archevo Design',
        'seo_services_description' => 'Plan approvals, interiors, civil construction, and turnkey projects from Archevo Design.',
        'seo_work_title' => 'Work | Archevo Design',
        'seo_work_description' => 'Selected residential, commercial, and retail projects by Archevo Design.',
        'seo_process_title' => 'Process | Archevo Design',
        'seo_process_description' => 'How Archevo Design moves from brief to handover — clear phases and accountability.',
        'seo_journal_title' => 'Journal | Archevo Design',
        'seo_journal_description' => 'Ideas on materiality, process, and the culture of space from Archevo Design.',
        'seo_contact_title' => 'Contact | Archevo Design',
        'seo_contact_description' => 'Contact Archevo Design in Rajkot for architecture and interior design enquiries.',
        'seo_privacy_title' => 'Privacy | Archevo Design',
        'seo_privacy_description' => 'Privacy policy for Archevo Infra Edge Pvt Ltd website.',
        'seo_terms_title' => 'Terms | Archevo Design',
        'seo_terms_description' => 'Terms of use for the Archevo Design website.',
        'seo_thanks_title' => 'Thank you | Archevo Design',
        'seo_thanks_description' => 'Thank you for contacting Archevo Design.',
    ];
}

function cms_build_copy_array(array $settings): array
{
    $defaults = cms_copy_defaults();
    $out = [];
    foreach (cms_copy_setting_keys() as $key => $label) {
        $out[$key] = trim((string) ($settings[$key] ?? '')) !== ''
            ? trim((string) $settings[$key])
            : ($defaults[$key] ?? '');
    }

    return $out;
}
